---
jobs:
- name: publish-unstable
  public: true
  plan:
  - aggregate:
    - get: opx-build
      version: latest
      trigger: true
    - get: base-image
      params:
        save: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      inputs:
      - name: opx-build
      - name: base-image
      outputs:
      - name: images
      params:
        REPO: opx-build
        OPX_DIST: unstable
      run:
        path: sh
        args:
        - -exc
        - |
          source /docker-lib.sh
          start_docker

          docker load -i base-image/image
          docker tag "$(cat base-image/image-id)" "$(cat base-image/repository):$(cat base-image/tag)"

          docker images

          cd $REPO
          sh -ex ./docker_build.sh
          cd ..
          docker save opxhub/build:$OPX_DIST -o images/build-$OPX_DIST.tar
          echo $OPX_DIST >images/$OPX_DIST
  - put: opxhub-build
    params:
      load_file: images/build-unstable.tar
      load_repository: opxhub/build
      load_tag: unstable
      tag: images/unstable
      tag_as_latest: true

- name: publish-testing
  public: true
  plan:
  - aggregate:
    - get: opx-build
      version: latest
      trigger: true
    - get: base-image
      params:
        save: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind
      inputs:
      - name: opx-build
      - name: base-image
      outputs:
      - name: images
      params:
        REPO: opx-build
        OPX_DIST: testing
      run:
        path: sh
        args:
        - -exc
        - |
          source /docker-lib.sh
          start_docker

          docker load -i base-image/image
          docker tag "$(cat base-image/image-id)" "$(cat base-image/repository):$(cat base-image/tag)"

          docker images

          cd $REPO
          sh -ex ./docker_build.sh
          cd ..
          docker save opxhub/build:$OPX_DIST -o images/build-$OPX_DIST.tar
          echo $OPX_DIST >images/$OPX_DIST
  - put: opxhub-build
    params:
      load_file: images/build-testing.tar
      load_repository: opxhub/build
      load_tag: testing
      tag: images/testing
      tag_as_latest: false

resources:
- name: opx-build
  type: git
  source:
    uri: git://git.openswitch.net/opx/opx-build
    branch: master
- name: opxhub-build
  type: docker-image
  source:
    repository: opxhub/build
    username: ((docker_hub_username))
    password: ((docker_hub_password))
- name: base-image
  type: docker-image
  source:
    repository: debian
    tag: jessie-backports
